### ISSUE TITLE
[Feature] findOne with email

### ISSUE THREAD

**Issue by dleurs** [xantiagoma/dart_strapi#1]
Hello,

It seems not possible to something like this at the moment.

strapi.query('restaurant').findOne({ name: 'restaurant name' });

For now, dart_strapi can only provides findOne with id.

Future<ContentType> findOne(String contentType, String id)

I would be a great feature

Thanks

**Comment by xantiagoma** [comment]
Hi @dleurs you maybe you could try with just `find`?

- https://strapi.io/documentation/v3.x/concepts/queries.html#api-reference
- https://pub.dev/documentation/dart_strapi/latest/dart_strapi/Strapi/find.html

Something like:

```dart
final records = await strapiClient.find('restaurant', queryParameters: {
    'name': 'restaurant name' ,
  });
final firstRecord = records.first;
```

You can even limit the records number if you just want the first record that matches the condition
```dart
final records = (await strapiClient.find('restaurant', queryParameters: {
        'name': 'restaurant name',
        '_limit': 1,
      }
    )
  ).first;
```

Does this solve your problem / Is that what you suggest? Take into account that it could be `null`. 😄

**Comment by dleurs** [comment]
Thank you for your answer, 

I wanted to use findOne in order to query if a specific email if set on strapi. So, the rule of findOne must be set to be available for unauthenticated user.
I cannot use find because it is too dangerous to leave find as available. No one should be able to get all emails. So, what I did is do some coding in js inside strapi.

I added in /api/user/config/routes.json 
```
{
  "routes": [
    {
      "method": "GET",
      "path": "/user/isemailexist/:email",
      "handler": "user.isEmailExist",
      "config": {
        "policies": []
      }
    }
  ]
}
```

And in I added in /api/user/controllers/user.json 
```
const { sanitizeEntity } = require('strapi-utils');
module.exports = {
  /**
   * Retrieve a record.
   *
   * @return {Object}
   */

  async isEmailExist(ctx) {
    console.log(ctx.params.email);
    const { email } = ctx.params;
    const entity = await strapi.plugins['users-permissions'].services.user.fetch({ email: email });
    if (entity == null) {
      ctx.response.status = 404;
      return ctx.response;
    }
    ctx.response.status = 302;
    return ctx.response;
  },
}; 
```

In order to use graphql I also added /api/user/config/schema.graphql.js
```
const { sanitizeEntity } = require('strapi-utils');
module.exports = {
  query: `
    isEmailExist(email: String): Boolean
  `,
  resolver: {
    Query: {
      isEmailExist: {
        plugin: 'users-permissions',
        resolverOf: 'User.isEmailExist',
        async resolver(ctx, { email }) {
            console.log(email);
            const entity = await strapi.plugins['users-permissions'].services.user.fetch({ email: email });
            if (entity == null) {
              return false;
            }
            return true;
          },
      },
    },
  },
};
```

Not sure it is clean js / strapi coding just it is working
Do I close the feature request ? Or leave it open ?
